// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bar: typeof import('./src/components/Bar.vue')['default']
    Baz: typeof import('./src/components/Baz.vue')['default']
    Echarts: typeof import('./src/components/Echarts.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElRow: typeof import('element-plus/es')['ElRow']
    Foo: typeof import('./src/components/Foo.vue')['default']
    User: typeof import('./src/components/User.vue')['default']
  }
}
